defmodule Aoc2024.Day6Test do
  use ExUnit.Case, async: true

  describe "part1" do
    test "example" do
      input = """
      ....#.....
      .........#
      ..........
      ..#.......
      .......#..
      ..........
      .#..^.....
      ........#.
      #.........
      ......#...
      """

      assert 41 = Aoc2024.Day6.part1(input)
    end
  end
end
