defmodule Aoc2024.Day8Test do
  use ExUnit.Case, async: true

  @input """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

  describe "part1" do
    test "example" do
      assert 14 = Aoc2024.Day8.part1(@input)
    end
  end

  describe "part2" do
    test "example" do
      assert 34 = Aoc2024.Day8.part2(@input)
    end
  end
end
